### ISSUE TITLE
从一个MainViewControll 以show的方式进入 TableViewControll的时候出错

### ISSUE THREAD

**Issue by nendors** [boyXiong/XWSwiftRefresh#1]
Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'An instance 0x7fec1b485b40 of class UIScrollViewPanGestureRecognizer was deallocated while key value observers were still registered with it. Current observation info: < NSKeyValueObservationInfo 0x7fec1b5e6820 > (
< NSKeyValueObservance 0x7fec1b556530: Observer: 0x7fec1b5e5800, Key path: state, Options: < New: YES, Old: NO, Prior: NO > Context: 0x0, Property: 0x7fec1b5e67f0 >)'

**Comment by boyXiong** [comment]
这边报错看不出具体的原因，如果可以，请给我看看部分代码，这样我好及时的修复

**Comment by nendors** [comment]
不是很懂github的使用 请见谅
就像我在你的demo的RootViewController(RVC)前面加多一个ViewController(VC)，该VC就一个Button跳转到RVC,当从RVC返回VC的时候就会报错
https://github.com/nendors/XWSwiftRefresh/tree/develop/Example

**Comment by boyXiong** [comment]
好的，我知道原因了，立马修复，谢谢

**Comment by boyXiong** [comment]
国庆玩了一下，已经修复，谢谢
