### ISSUE TITLE
cocoapod 的引入使用问题

### ISSUE THREAD

**Issue by mouse-lin** [boyXiong/XWSwiftRefresh#2]
cocoapod 引入使用有试过么？我看到所有的 class  都不是 public 的，所以不是会导致外部引用不到么？

**Comment by boyXiong** [comment]
0.0 之前没测试 ，我会去修复它，谢谢, 你也可以先直接DownLoad 后，拖拽进去，就可以使用

**Comment by boyXiong** [comment]
已经修复 版本更新到 0.1.3 详情请看 readme 谢谢 支持

**Comment by mouse-lin** [comment]
@boyXiong got it

**Comment by boyXiong** [comment]
请用最新的 0.1.6
